### ISSUE TITLE
Getting negetive wallclock time in the sparklens UI

### ISSUE THREAD

**Issue by shahidki31** [qubole/sparklens#44]
Hi,
 Thank you for the amazing tool for the performance monitoring of spark jobs. I was trying out some long running spark query using sparklens. However I was getting some strange output in the sparklens UI regarding the job time,  like wallclock time etc.
![image](https://user-images.githubusercontent.com/23054875/63600952-283edd00-c5e2-11e9-9610-260aea64fc61.png)
![image](https://user-images.githubusercontent.com/23054875/63600989-3987e980-c5e2-11e9-8971-ba69dcae70c8.png)
Could you please help me to resolve this issue?

**Comment by iamrohit** [comment]
@shahidki31 Thanks for raising this. We will take a look at get back to you.
I know of couple of reasons why this happens. The first one is missing job end events in the event log file. When the job end time is not known, we try to estimate it. If these are bad estimates, we can run into negative job time issues. The second reason is multiple jobs running in parallel. Sparklens computes driver time by subtracting "time spent in jobs" from the total wall clock time. With parallel jobs, it becomes a bit tricky to find out "time spent in jobs". We had made some changes to deal with this problem, but perhaps running is something new here.  We will check and get back to you.

**Comment by mayurdb** [comment]
@shahidki31 Parallel jobs were not getting considered at one place in the code, which is why you were getting a negative driver wallclock time. I have fixed it and updated the jar. Please check now, it should work correctly. Thanks for reporting 👍

**Comment by shahidki31** [comment]
Thanks @iamrohit @mayurdb for the replies. Yes, I am running jobs in parallel (TPCDS queries basically).  Seems, console output is giving the correct results, only UI has the problem. Will check again. Thank you.
