### ISSUE TITLE
Sparklens with spark-submit

### ISSUE THREAD

**Issue by akumarb2010** [qubole/sparklens#7]
Once we run the spark application with spark-submit by adding below sparklens configs, where can we find the sparklens results? Or does Sparklens only works with notebooks?

```
--packages qubole:sparklens:0.1.2-s_2.11
--conf spark.extraListeners=com.qubole.sparklens.QuboleJobListener
```

**Comment by iamrohit** [comment]
Check the driver logs.

**Comment by akumarb2010** [comment]
Thanks for quick response. I am able to see these reports logged into Driver logs.

Just for quick check,  is there any web interface for accessing reports as mentioned in https://www.qubole.com/blog/introducing-quboles-spark-tuning-tool/ ?  Just wanted to understand critical path for our use cases.

**Comment by iamrohit** [comment]
No we don't yet have any UI to view this. We do print the length (time taken) in the critical path. Look for text like:
`Minimum possible time for the app based on the critical path (with infinite resources) `

**Comment by akumarb2010** [comment]
Thanks for the details @iamrohit . It's very helpful.
