### ISSUE TITLE
pyspark  can use sparklens?

### ISSUE THREAD

**Issue by ghost** [qubole/sparklens#72]
i have a pyspark program.
spark 2.4.0 , hadoop 3.0.0
use  spark-submit --jars sparklens-0.3.2-s_2.11.jar  --conf spark.extraListeners=com.qubole.sparklens.QuboleJobListener --conf spark.sparklens.reporting.disabled=true
to submit the pyspark program.
but error accure, anybody know why?
![727433568511414356](https://user-images.githubusercontent.com/1522163/132642736-3c2e9da8-c28c-4f08-8365-2268f6261b54.png)

**Comment by rpatid10** [comment]
@jiemar  Looks like it is  some other issue with your code  not with sparkLense .can u try to run it without using  --jars sparklens-0.3.2-s_2.11.jar  --conf spark.extraListeners=com.qubole.sparklens.QuboleJobListener --conf spark.sparklens.reporting.disabled=true and see if it showing same issue or not.
